// openscore-ui/src/app/views/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  templateUrl: 'dashboard.component.html'
})
export class DashboardComponent {

  clock: string;
  comienzo = new Date(2018, 5, 14);

  constructor() {
    this.clock = this.getRemainingDays();
    setInterval(() => {
      this.clock = this.getRemainingDays();
    }, 1000);

  }

  getRemainingDays() {
    const time = this.comienzo.getTime() - new Date().getTime();
    return (time / (1000 * 60 * 60 * 24)).toFixed();
  }



}

<div class="animated fadeIn">
  <h1>Dashboard</h1>

  <div class="row">
    <div class="col-sm-6 col-lg-3" [hidden]="true">
      <!-- <ngx-twitter-timeline [data]="{
        sourceType: 'url',
        url: 'https://twitter.com/fifaworldcup'}" [opts]="{
        tweetLimit: 0
    }"></ngx-twitter-timeline> -->
    </div>

    <div class="col-sm-6 col-lg-3">
      <div class="card text-white bg-info">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ matches }}</h4>
          <p>Matches today</p>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-lg-3">
      <div class="card text-white bg-danger">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ finalClock }}</h4>
          <p>Days until Final match</p>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-lg-3">
      <div class="card text-white bg-info">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ argentinos }}</h4>
          <p>Argentineans/SolaEast registered</p>
          <ol>
            <li *ngFor="let e of arg">{{ e.puntos }} - {{ e.nombre }}</li>
          </ol>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-lg-3">
      <div class="card text-white bg-warning">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ brasileros }}</h4>
          <p>Brazilians registered</p>
          <ol>
            <li *ngFor="let e of bra">{{ e.puntos }} - {{ e.nombre }}</li>
          </ol>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-lg-3">
      <div class="card text-white bg-success">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ mexicanos }}</h4>
          <p>Mexicans registered</p>
          <ol>
            <li *ngFor="let e of mex">{{ e.puntos }} - {{ e.nombre }}</li>
          </ol>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-lg-3">
      <div class="card text-white bg-warning">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ colombianos }}</h4>
          <p>Colombians/CEACA registered</p>
          <ol>
            <li *ngFor="let e of col">{{ e.puntos }} - {{ e.nombre }}</li>
          </ol>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-lg-3">
      <div class="card text-white bg-danger">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ chilenos }}</h4>
          <p>Chileans registered</p>
          <ol>
            <li *ngFor="let e of chi">{{ e.puntos }} - {{ e.nombre }}</li>
          </ol>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-lg-3">
      <div class="card text-white bg-danger">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ peruanos }}</h4>
          <p>Peruvians registered</p>
          <ol>
            <li *ngFor="let e of per">{{ e.puntos }} - {{ e.nombre }}</li>
          </ol>
        </div>
      </div>
    </div>

    <!-- <div class="col-sm-6 col-lg-12">
      <a class="twitter-grid" data-partner="tweetdeck" href="https://twitter.com/adrielparedes/timelines/1005814401990000640?ref_src=twsrc%5Etfw">WorldCup</a>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </div> -->
  </div>
</div>

// packages/openscore-nextjs/pages/dashboard.tsx
import { layout } from "../components/layout/MainLayout";
import { NextPageWithLayout } from "./_app";

const Dashboard: NextPageWithLayout = () => {
  return (
    <div className="animated fadeIn">
      <h1>Dashboard</h1>

      <div className="row">
        <div className="col-sm-6 col-lg-3"></div>

        <div className="col-sm-6 col-lg-3">
          <div className="card text-white bg-info">
            <div className="card-body pb-0">
              <h4 className="mb-0"> </h4>
              <p>Matches today</p>
            </div>
          </div>
        </div>

        <div className="col-sm-6 col-lg-3">
          <div className="card text-white bg-danger">
            <div className="card-body pb-0">
              <h4 className="mb-0"></h4>
              <p>Days until Final match</p>
            </div>
          </div>
        </div>

        <div className="col-sm-6 col-lg-3">
          <div className="card text-white bg-info">
            <div className="card-body pb-0">
              <h4 className="mb-0"></h4>
              <p>Argentineans/SolaEast registered</p>
              <ol></ol>
            </div>
          </div>
        </div>

        <div className="col-sm-6 col-lg-3">
          <div className="card text-white bg-warning">
            <div className="card-body pb-0">
              <h4 className="mb-0"></h4>
              <p>Brazilians registered</p>
              <ol></ol>
            </div>
          </div>
        </div>

        <div className="col-sm-6 col-lg-3">
          <div className="card text-white bg-success">
            <div className="card-body pb-0">
              <h4 className="mb-0"></h4>
              <p>Mexicans registered</p>
              <ol></ol>
            </div>
          </div>
        </div>

        <div className="col-sm-6 col-lg-3">
          <div className="card text-white bg-warning">
            <div className="card-body pb-0">
              <h4 className="mb-0"></h4>
              <p>Colombians/CEACA registered</p>
              <ol></ol>
            </div>
          </div>
        </div>

        <div className="col-sm-6 col-lg-3">
          <div className="card text-white bg-danger">
            <div className="card-body pb-0">
              <h4 className="mb-0"></h4>
              <p>Chileans registered</p>
              <ol></ol>
            </div>
          </div>
        </div>

        <div className="col-sm-6 col-lg-3">
          <div className="card text-white bg-danger">
            <div className="card-body pb-0">
              <h4 className="mb-0"></h4>
              <p>Peruvians registered</p>
              <ol></ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

Dashboard.getLayout = layout;

export default Dashboard;
